using System;

public class PromptGenerator
{

    string[] _prompts = new string[]
    {
        "What's the highlight of your week so far?",
        "Did anything exciting happen to you today?",
        "What have you been up to recently?",
        "Have you discovered any new hobbies lately?",
        "What's been the best part of your day?",
        "How are you feeling today?",
        "Any interesting plans for the weekend?",
        "What did you have for lunch/dinner?",
        "Did you watch any good movies or shows recently?",
        "Have you read any good books lately?",
        "What's your favorite way to unwind after a long day?",
        "Any fun projects you're working on?",
        "What's something new you learned today?",
        "Have you visited any cool places recently?",
        "What music have you been listening to?",
        "Did you have any interesting conversations today?",
        "What's the most memorable part of your day?",
        "Any exciting news to share?",
        "How's the weather treating you?",
        "Have you tried any new recipes or restaurants recently?",
        "What's your go-to way to relax?",
        "Any fun adventures planned?",
        "How's work/school going for you?",
        "What's been keeping you busy lately?",
        "Any new goals or resolutions?",
        "Have you picked up any new skills or talents recently?",
        "What is something you are looking forward to?",
        "How do you like to spend your free time?",
        "What's the funniest thing that happened to you today?",
        "Have you attended any events or gatherings recently?",
        "What's your favorite way to spend a lazy Sunday?",
        "Did you encounter any challenges today?",
        "How do you stay motivated during the week?",
        "Have you met anyone interesting recently?",
        "What's your favorite way to start the day?",
        "Any favorite podcasts or radio shows?",
        "What's your current favorite snack?",
        "Did you see any interesting news stories today?",
        "How do you stay organized with your tasks?",
        "Any interesting observations from today?",
        "Have you been working on any creative projects?",
        "What's your favorite way to get some fresh air?",
        "Did you have any unexpected surprises today?",
        "What's your favorite way to spend a rainy day?",
        "Any exciting travel plans coming up?",
        "How do you stay positive and motivated?",
        "What's the best compliment you've received recently?",
        "Have you caught up with any old friends lately?",
        "What's your go-to way to de-stress?",
        "Did you have any 'aha' moments today?",
        "What's your favorite way to stay active?",
        "How do you stay connected with loved ones?",
        "What's your favorite way to end the day?",
        "Did you encounter any funny or unusual situations today?",
        "How do you manage your time effectively?",
        "Any cool apps or tools you've discovered recently?",
        "What's your favorite way to celebrate small victories?",
        "Did you try anything new today?",
        "How do you handle busy days?",
        "Any exciting updates on your life?",
        "What's your favorite way to boost your mood?",
        "Did you have any meaningful conversations today?",
        "How do you like to treat yourself?",
        "Any interesting articles or videos you came across recently?",
        "What's your favorite way to unwind before bed?",
        "Did you accomplish any goals today?",
        "How do you stay focused throughout the day?",
        "Any inspiring quotes or thoughts on your mind?",
        "What's the most interesting thing you learned today?",
        "How do you handle unexpected changes in your plans?",
        "Any fun weekend plans?",
        "What's your favorite way to recharge?",
        "Did you notice anything beautiful or interesting today?",
        "How do you stay productive during the day?",
        "Any hobbies you're passionate about?",
        "What's your favorite way to spend quality time with others?",
        "Did you experience any acts of kindness today?",
        "How do you keep a positive mindset?",
        "Any exciting discoveries or realizations?",
        "What's your favorite way to explore new places?",
        "Did you have any memorable interactions today?",
        "How do you stay organized and on top of things?",
        "Any new trends or topics you're curious about?",
        "What's your favorite way to stay entertained?",
        "Did you have any moments of reflection today?",
        "How do you like to pamper yourself?",
        "Any new routines or habits you've started?",
        "What's your favorite way to relax after a busy day?",
        "Did you encounter any challenges or obstacles today?",
        "How do you stay motivated and inspired?",
        "Any recent accomplishments you're proud of?",
        "What's your favorite way to spend a sunny day?",
        "Did you try anything different today?",
        "How do you handle stressful situations?",
        "Any new adventures on the horizon?",
        "What's your favorite way to show appreciation to others?",
        "Did you have any unexpected laughs today?",
        "How do you like to stay creative?",
        "Any fun memories from today?",
        "What's your favorite way to stay connected with your community?"
        };

    public string GetRandomPrompt()
    {
        Random random = new Random();
        int index = random.Next(_prompts.Length);
        return _prompts[index];
    }
    
}